name = "anime-gifs"
main = "src/index.js"
compatibility_date = "2022-12-02"
account_id = "bfb2e522e0b245720424784fcf7c04c0"

[[ d1_databases ]]
binding = "DB" # available in your Worker on `env.DB`
database_name = "anime-gifs"
database_id = "4db71605-0b7d-4ee4-bc21-c574c97d0a42"
preview_database_id = "df801c9d-d264-4dad-b32e-b79628e0b656"
