on:
  push:
    branches:
      - master

name: Deploy to Cloudflare Workers

jobs:
  deploy-worker:
    runs-on: ubuntu-latest
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Deploy to Cloudflare
        uses: cloudflare/wrangler-action@2.0.0
          apiToken: ${{ secrets.CF_API_TOKEN }}

